### ISSUE TITLE
Update to KSP 1.9.1

### ISSUE THREAD

**Issue by KRtekTM** [ihsoft/EasyVesselSwitch#28]
Hello, I really like the EasyVesselSwitch mod and waiting for an updated version to be compatible with KSP 1.9.1
Will it happen?
Thanks!

**Comment by ihsoft** [comment]
Hello. As far as can tell, the latest version runs just fine in 1.9.1. It complains about incompatible version, but it's just a check for the number. No real issues are known this far.

I'll fix the checked version soon to remove the annoying notice.
