### ISSUE TITLE
Conflict with stock building system 

### ISSUE THREAD

**Issue by eberkain** [ihsoft/EasyVesselSwitch#34]
The new in-flight construction system in stock conflicts with the use of the alt key.  

In the construction mode you will see attachment nodes, but parts will always surface attach instead. To override the surface attach behavior and attach to nodes you use the ALT key just as you can do in the editor.  

Since you are controlling a kerbal to build, and you just alt-clicked on another craft to attach a part to a node, it switches you to the other craft and can bug out the ui, getting you into a state where you can't access the main menu.  The part that you were attaching will go flying and if you are lucky, not break anything.  

I recommend disabling the EVS mechanic while in the construction mode as a solution.

**Comment by ihsoft** [comment]
Thanks for reporting. It makes sense to disable switching in the builder mode. Meanwhile you can change the EVS binding in the settings file.
